site_name: Owl Framework Docs
theme: yeti
repo_url: https://github.com/owl-framework/docs/
site_author: Dmitry Patsura @ovr
copyright: Owl Team and Contributors
pages:
  - [index.md, Home]
  - [cache.md, Cache]